#' NYC Taxi trip data from NYC's Taxi and Limousine Commission (TLC)
#' @author Wencong (Priscilla) Li
#' @description Random samples of 1000 observations generated by the 'sample' function 
#' in base R from the 2016 January green and yellow taxi trip data.
#' 
#' @details NYC's Taxi and Limousine Commission (TLC) Trip Data is a collection of trip records 
#' including fields capturing pick-up and drop-off locations, times, trip distances, fares, rate types, 
#' and driver-reported passenger counts. The data was collected and provided to the NYC TLC by 
#' technology providers under the Taxicab & Livery Passenger Enhancement Programs. 
#' 
#' @docType data
#' @format For both, a dataframe (\code{\link[dplyr]{tbl_df}}) each with 1,000 rows and 21 or 19 variables.
#' 
#' The following variables are values that are found in either the \code{green_2016_01_sample}
#' or \code{yellow_2016_01_sample} data tables.
#' 
#' \describe{
#'   \item{VendorID}{}
#'   \item{lpep_pickup_datetime}{Taxi pickup date and time}
#'   \item{lpep_dropoff_datetime}{Taxi dropoff date and time}
#'   \item{lpep_pickup_datetime}{Taxi pickup date and time}
#'   \item{lpep_dropoff_datetime}{Taxi dropoff date and time}
#'   \item{Store_and_fwd_flag}{}
#'   \item{RareCodeID}{}
#'   \item{Pickup_longitude}{Pickup location's longitude}
#'   \item{Pickup_latitude}{Pickup location's latitude}
#'   \item{Dropoff_longtitude}{Dropoff location's longitude}
#'   \item{Dropoff_latitude}{Dropoff location's latitude}
#'   \item{Passenger_count}{Number of passengers for a trip}
#'   \item{Trip_distance}{The trip distance in miles}
#'   \item{Fare_amount}{The price of a trip}
#'   \item{Extra}{Extra fee charged for a trip}
#'   \item{MTA_tax}{}
#'   \item{Tip_amount}{The amount of tips paid by the passenger(s)}
#'   \item{Tolls_amount}{}
#'   \item{Ehail_fee}{}
#'   \item{improvement_surcharge}{}
#'   \item{Total amount}{Total amount paid for a trip}
#'   \item{Payment_type}{}
#'   \item{Trip_type}{}
#' }
#' 
#' @source These data are recorded at \url{http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml} 
#' 
"green_2016_01_sample"

#' @rdname green_2016_01_sample
#' @examples 
#' \dontrun{
#' #' # 
#' if (require(dplyr) & require(ggplot2)) {
#'  green_2016_01_sample %>%
#'  filter(Trip_distance <= 1) %>%
#'    ggplot(aes(x = Dropoff_longtitude, y = Pickup_latitude))
#' }
#' }
#' 
"yellow_2016_01_sample"

#' 
#' 
#' 